"""initial schema

Revision ID: 01ccc8e42496
Revises: 
Create Date: 2026-04-15 11:05:02.360637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01ccc8e42496'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Account', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Account', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Account', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('Account', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('Account', 'providerAccountId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('Account', 'token_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('Account', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('Account', 'session_state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('Account_provider_providerAccountId_key'), table_name='Account')
    op.create_unique_constraint('uq_accounts_provider', 'Account', ['provider', 'providerAccountId'])
    op.drop_constraint(op.f('Account_userId_fkey'), 'Account', type_='foreignkey')
    op.create_foreign_key(None, 'Account', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('Session', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Session', 'sessionToken',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('Session', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Session', 'expires',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('Session_sessionToken_key'), table_name='Session')
    op.create_unique_constraint(None, 'Session', ['sessionToken'])
    op.drop_constraint(op.f('Session_userId_fkey'), 'Session', type_='foreignkey')
    op.create_foreign_key(None, 'Session', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('User', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('User', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('User', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('User', 'emailVerified',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('User', 'image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('User', 'stripeCustomerId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('User', 'subscriptionId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('User', 'plan',
               existing_type=postgresql.ENUM('FREE', 'PRO', 'PREMIUM', name='Plan'),
               type_=sa.Enum('FREE', 'PRO', 'PREMIUM', name='plan', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text('\'FREE\'::"Plan"'))
    op.alter_column('User', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('User', 'trialEndsAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('User_email_key'), table_name='User')
    op.drop_index(op.f('User_stripeCustomerId_key'), table_name='User')
    op.drop_index(op.f('User_subscriptionId_key'), table_name='User')
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_unique_constraint(None, 'User', ['stripeCustomerId'])
    op.create_unique_constraint(None, 'User', ['subscriptionId'])
    op.alter_column('VerificationCode', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('VerificationCode', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('VerificationCode', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('VerificationCode', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('VerificationCode', 'expiresAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('VerificationCode', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('VerificationCode_email_code_idx'), table_name='VerificationCode')
    op.create_index('ix_verification_codes_email_code', 'VerificationCode', ['email', 'code'], unique=False)
    op.drop_constraint(op.f('VerificationCode_userId_fkey'), 'VerificationCode', type_='foreignkey')
    op.create_foreign_key(None, 'VerificationCode', 'User', ['userId'], ['id'])
    op.alter_column('WebhookEvent', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('WebhookEvent', 'stripeEventId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('WebhookEvent', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('WebhookEvent', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('WebhookEvent', 'processedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('WebhookEvent', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('WebhookEvent_stripeEventId_key'), table_name='WebhookEvent')
    op.create_unique_constraint(None, 'WebhookEvent', ['stripeEventId'])
    op.drop_constraint(op.f('WebhookEvent_userId_fkey'), 'WebhookEvent', type_='foreignkey')
    op.create_foreign_key(None, 'WebhookEvent', 'User', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'WebhookEvent', type_='foreignkey')
    op.create_foreign_key(op.f('WebhookEvent_userId_fkey'), 'WebhookEvent', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'WebhookEvent', type_='unique')
    op.create_index(op.f('WebhookEvent_stripeEventId_key'), 'WebhookEvent', ['stripeEventId'], unique=True)
    op.alter_column('WebhookEvent', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('WebhookEvent', 'processedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('WebhookEvent', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('WebhookEvent', 'type',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('WebhookEvent', 'stripeEventId',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('WebhookEvent', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'VerificationCode', type_='foreignkey')
    op.create_foreign_key(op.f('VerificationCode_userId_fkey'), 'VerificationCode', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index('ix_verification_codes_email_code', table_name='VerificationCode')
    op.create_index(op.f('VerificationCode_email_code_idx'), 'VerificationCode', ['email', 'code'], unique=False)
    op.alter_column('VerificationCode', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('VerificationCode', 'expiresAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False)
    op.alter_column('VerificationCode', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('VerificationCode', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('VerificationCode', 'code',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('VerificationCode', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.create_index(op.f('User_subscriptionId_key'), 'User', ['subscriptionId'], unique=True)
    op.create_index(op.f('User_stripeCustomerId_key'), 'User', ['stripeCustomerId'], unique=True)
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.alter_column('User', 'trialEndsAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('User', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('User', 'plan',
               existing_type=sa.Enum('FREE', 'PRO', 'PREMIUM', name='plan', native_enum=False),
               type_=postgresql.ENUM('FREE', 'PRO', 'PREMIUM', name='Plan'),
               existing_nullable=False,
               existing_server_default=sa.text('\'FREE\'::"Plan"'))
    op.alter_column('User', 'subscriptionId',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('User', 'stripeCustomerId',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('User', 'image',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('User', 'emailVerified',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('User', 'password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('User', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Session', type_='foreignkey')
    op.create_foreign_key(op.f('Session_userId_fkey'), 'Session', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'Session', type_='unique')
    op.create_index(op.f('Session_sessionToken_key'), 'Session', ['sessionToken'], unique=True)
    op.alter_column('Session', 'expires',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False)
    op.alter_column('Session', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Session', 'sessionToken',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Session', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Account', type_='foreignkey')
    op.create_foreign_key(op.f('Account_userId_fkey'), 'Account', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('uq_accounts_provider', 'Account', type_='unique')
    op.create_index(op.f('Account_provider_providerAccountId_key'), 'Account', ['provider', 'providerAccountId'], unique=True)
    op.alter_column('Account', 'session_state',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Account', 'scope',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Account', 'token_type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Account', 'providerAccountId',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Account', 'provider',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Account', 'type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Account', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Account', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
